packages:
  - extras/*
  - packages/*
  - packages/services/*
  - packages/utils/*
  - packages/wallet/*
  - repo/*
  - test/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - lefthook
  - prisma
  - protobufjs
  - secp256k1
  - sharp
  - utf-8-validate
  - web3
  - web3-bzz

overrides:
  0xsequence.js.git: link:.local/share/pnpm/global/5/node_modules/https:/github.com/Dargon789/0xsequence.js.git
  Rabby.git: link:.local/share/pnpm/global/5/node_modules/git@github.com:Dargon789/Rabby.git
  braces@<3.0.3: '>=3.0.3'
  cookie@<0.7.0: '>=0.7.0'
  diff@<4.0.4: '>=4.0.4'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  form-data@<2.5.4: '>=2.5.4'
  happy-dom@<20.0.0: '>=20.0.0'
  hardhat-project.git: link:.local/share/pnpm/global/5/node_modules/git@github.com:Dargon789/hardhat-project.git
  hono@<4.11.7: '>=4.11.7'
  http-proxy-middleware@<2.0.7: '>=2.0.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  micromatch@<4.0.8: '>=4.0.8'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
  node-forge@<1.0.0: '>=1.0.0'
  node-forge@<1.3.0: '>=1.3.0'
  node-forge@<1.3.2: '>=1.3.2'
  qs@<6.14.1: '>=6.14.1'
  semver@<5.7.2: '>=5.7.2'
  tar@<6.2.1: '>=6.2.1'
  tar@<=7.5.2: '>=7.5.3'
  thirdweb-dev.git: link:.local/share/pnpm/global/5/node_modules/git@github.com:Dargon789/thirdweb-dev.git
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  undici@<5.29.0: '>=5.29.0'
  undici@<6.23.0: '>=6.23.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  wallet-contracts.git: link:.local/share/pnpm/global/5/node_modules/https:/github.com/Dargon789/wallet-contracts.git
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  ws@>=2.1.0 <5.2.4: '>=5.2.4'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
  xml2js@<0.5.0: '>=0.5.0'

publicHoistPattern:
  - eslint
