packages:
  - extras/*
  - packages/*
  - packages/services/*
  - packages/utils/*
  - packages/wallet/*
  - repo/*
  - test/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - lefthook
  - sharp
  - utf-8-validate

publicHoistPattern:
  - eslint
