// Automatically generated by forge bind-json.

pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {MainModuleGasEstimation} from "contracts/modules/MainModuleGasEstimation.sol";
import {IModuleCalls} from "contracts/modules/commons/interfaces/IModuleCalls.sol";
import {ModuleCallsTest} from "foundry_test/modules/commons/ModuleCalls.t.sol";
import {ModuleExtraAuthTest} from "foundry_test/modules/commons/ModuleExtraAuth.t.sol";
import {SequenceChainedSigImp, SequenceChainedSigTest} from "foundry_test/modules/commons/submodules/auth/SequenceChainedSig.t.sol";
import {L2CompressorHuffTest} from "foundry_test/modules/utils/L2CompressorHuff.t.sol";
import {TrustTest} from "foundry_test/trust/Trust.t.sol";

interface Vm {
    function parseJsonTypeArray(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function serializeJsonType(string calldata typeDescription, bytes memory value) external pure returns (string memory json);
    function serializeJsonType(string calldata objectKey, string calldata valueKey, string calldata typeDescription, bytes memory value) external returns (string memory json);
}
        
library JsonBindings {
    Vm constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    string constant schema_Transaction = "Transaction(bool delegateCall,bool revertOnError,uint256 gasLimit,address target,uint256 value,bytes data)";
    string constant schema_SimulateResult = "SimulateResult(bool executed,bool succeeded,bytes result,uint256 gasUsed)";
    string constant schema_ToValAndData = "ToValAndData(address target,uint256 value,bytes data)";
    string constant schema_SetIh = "SetIh(bytes32 imageHash,uint256 expiration)";
    string constant schema_MockedSignature = "MockedSignature(bool exists,uint256 threshold,uint256 weight,bytes32 imageHash,bytes32 subdigest,uint256 checkpoint)";
    string constant schema_HashAndSignature = "HashAndSignature(bytes32 imageHash,uint256 threshold,uint256 weight,uint56 checkpointDelta,bytes signature)";
    string constant schema_BatchMember = "BatchMember(Transaction[] txs,uint160 space,uint96 nonce,bytes signature)Transaction(bool delegateCall,bool revertOnError,uint256 gasLimit,address target,uint256 value,bytes data)";
    string constant schema_MemoryStruct1 = "MemoryStruct1(bytes32 rawHash,bytes32 finalHash,uint8 v,bytes32 r,bytes32 s)";

    function serialize(IModuleCalls.Transaction memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Transaction, abi.encode(value));
    }

    function serialize(IModuleCalls.Transaction memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Transaction, abi.encode(value));
    }

    function deserializeTransaction(string memory json) public pure returns (IModuleCalls.Transaction memory) {
        return abi.decode(vm.parseJsonType(json, schema_Transaction), (IModuleCalls.Transaction));
    }

    function deserializeTransaction(string memory json, string memory path) public pure returns (IModuleCalls.Transaction memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Transaction), (IModuleCalls.Transaction));
    }

    function deserializeTransactionArray(string memory json, string memory path) public pure returns (IModuleCalls.Transaction[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Transaction), (IModuleCalls.Transaction[]));
    }

    function serialize(MainModuleGasEstimation.SimulateResult memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SimulateResult, abi.encode(value));
    }

    function serialize(MainModuleGasEstimation.SimulateResult memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SimulateResult, abi.encode(value));
    }

    function deserializeSimulateResult(string memory json) public pure returns (MainModuleGasEstimation.SimulateResult memory) {
        return abi.decode(vm.parseJsonType(json, schema_SimulateResult), (MainModuleGasEstimation.SimulateResult));
    }

    function deserializeSimulateResult(string memory json, string memory path) public pure returns (MainModuleGasEstimation.SimulateResult memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SimulateResult), (MainModuleGasEstimation.SimulateResult));
    }

    function deserializeSimulateResultArray(string memory json, string memory path) public pure returns (MainModuleGasEstimation.SimulateResult[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SimulateResult), (MainModuleGasEstimation.SimulateResult[]));
    }

    function serialize(ModuleCallsTest.ToValAndData memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_ToValAndData, abi.encode(value));
    }

    function serialize(ModuleCallsTest.ToValAndData memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_ToValAndData, abi.encode(value));
    }

    function deserializeToValAndData(string memory json) public pure returns (ModuleCallsTest.ToValAndData memory) {
        return abi.decode(vm.parseJsonType(json, schema_ToValAndData), (ModuleCallsTest.ToValAndData));
    }

    function deserializeToValAndData(string memory json, string memory path) public pure returns (ModuleCallsTest.ToValAndData memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_ToValAndData), (ModuleCallsTest.ToValAndData));
    }

    function deserializeToValAndDataArray(string memory json, string memory path) public pure returns (ModuleCallsTest.ToValAndData[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_ToValAndData), (ModuleCallsTest.ToValAndData[]));
    }

    function serialize(ModuleExtraAuthTest.SetIh memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SetIh, abi.encode(value));
    }

    function serialize(ModuleExtraAuthTest.SetIh memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SetIh, abi.encode(value));
    }

    function deserializeSetIh(string memory json) public pure returns (ModuleExtraAuthTest.SetIh memory) {
        return abi.decode(vm.parseJsonType(json, schema_SetIh), (ModuleExtraAuthTest.SetIh));
    }

    function deserializeSetIh(string memory json, string memory path) public pure returns (ModuleExtraAuthTest.SetIh memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SetIh), (ModuleExtraAuthTest.SetIh));
    }

    function deserializeSetIhArray(string memory json, string memory path) public pure returns (ModuleExtraAuthTest.SetIh[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SetIh), (ModuleExtraAuthTest.SetIh[]));
    }

    function serialize(SequenceChainedSigImp.MockedSignature memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_MockedSignature, abi.encode(value));
    }

    function serialize(SequenceChainedSigImp.MockedSignature memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_MockedSignature, abi.encode(value));
    }

    function deserializeMockedSignature(string memory json) public pure returns (SequenceChainedSigImp.MockedSignature memory) {
        return abi.decode(vm.parseJsonType(json, schema_MockedSignature), (SequenceChainedSigImp.MockedSignature));
    }

    function deserializeMockedSignature(string memory json, string memory path) public pure returns (SequenceChainedSigImp.MockedSignature memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_MockedSignature), (SequenceChainedSigImp.MockedSignature));
    }

    function deserializeMockedSignatureArray(string memory json, string memory path) public pure returns (SequenceChainedSigImp.MockedSignature[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_MockedSignature), (SequenceChainedSigImp.MockedSignature[]));
    }

    function serialize(SequenceChainedSigTest.HashAndSignature memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_HashAndSignature, abi.encode(value));
    }

    function serialize(SequenceChainedSigTest.HashAndSignature memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_HashAndSignature, abi.encode(value));
    }

    function deserializeHashAndSignature(string memory json) public pure returns (SequenceChainedSigTest.HashAndSignature memory) {
        return abi.decode(vm.parseJsonType(json, schema_HashAndSignature), (SequenceChainedSigTest.HashAndSignature));
    }

    function deserializeHashAndSignature(string memory json, string memory path) public pure returns (SequenceChainedSigTest.HashAndSignature memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_HashAndSignature), (SequenceChainedSigTest.HashAndSignature));
    }

    function deserializeHashAndSignatureArray(string memory json, string memory path) public pure returns (SequenceChainedSigTest.HashAndSignature[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_HashAndSignature), (SequenceChainedSigTest.HashAndSignature[]));
    }

    function serialize(L2CompressorHuffTest.BatchMember memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_BatchMember, abi.encode(value));
    }

    function serialize(L2CompressorHuffTest.BatchMember memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_BatchMember, abi.encode(value));
    }

    function deserializeBatchMember(string memory json) public pure returns (L2CompressorHuffTest.BatchMember memory) {
        return abi.decode(vm.parseJsonType(json, schema_BatchMember), (L2CompressorHuffTest.BatchMember));
    }

    function deserializeBatchMember(string memory json, string memory path) public pure returns (L2CompressorHuffTest.BatchMember memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_BatchMember), (L2CompressorHuffTest.BatchMember));
    }

    function deserializeBatchMemberArray(string memory json, string memory path) public pure returns (L2CompressorHuffTest.BatchMember[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_BatchMember), (L2CompressorHuffTest.BatchMember[]));
    }

    function serialize(TrustTest.MemoryStruct1 memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_MemoryStruct1, abi.encode(value));
    }

    function serialize(TrustTest.MemoryStruct1 memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_MemoryStruct1, abi.encode(value));
    }

    function deserializeMemoryStruct1(string memory json) public pure returns (TrustTest.MemoryStruct1 memory) {
        return abi.decode(vm.parseJsonType(json, schema_MemoryStruct1), (TrustTest.MemoryStruct1));
    }

    function deserializeMemoryStruct1(string memory json, string memory path) public pure returns (TrustTest.MemoryStruct1 memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_MemoryStruct1), (TrustTest.MemoryStruct1));
    }

    function deserializeMemoryStruct1Array(string memory json, string memory path) public pure returns (TrustTest.MemoryStruct1[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_MemoryStruct1), (TrustTest.MemoryStruct1[]));
    }
}
